---
deployment:
  tasks:
    - /bin/date > /home/efinitys/deploy-log.txt 2>&1
    - /usr/bin/whoami >> /home/efinitys/deploy-log.txt 2>&1
    - /usr/bin/which rsync >> /home/efinitys/deploy-log.txt 2>&1
    - /bin/echo "--- rsync output ---" >> /home/efinitys/deploy-log.txt 2>&1
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='error_log' /home/efinitys/repositories/padel-signup/ /home/efinitys/playpadelwith.us/ >> /home/efinitys/deploy-log.txt 2>&1
