---
deployment:
  tasks:
    - /bin/date > /home/efinitys/deploy-log.txt 2>&1
    - /bin/rm -rf /home/efinitys/playpadelwith.us/.git
    - /usr/bin/tar -C /home/efinitys/repositories/padel-signup --exclude='./.git' --exclude='./.cpanel.yml' -cf - . | /usr/bin/tar -C /home/efinitys/playpadelwith.us -xpf - 2>> /home/efinitys/deploy-log.txt
    - /bin/echo "Deploy finished at $(/bin/date)" >> /home/efinitys/deploy-log.txt 2>&1
